- name: ansible web app
  hosts: web
  become: yes
  tasks:
    - name: copy war file
      copy:
       src: "/var/snap/jenkins/4874/workspace/ansibleExternal/target/MavenAnsibleWebApp.war"
       dest: "/opt/tomcat/webapps/MavenAnsibleWebApp.war"
       remote_src: no
    - name: restart tomcat
      systemd:
      	name: tomcat
      	state: restart      	
